spring.application.name=voting


spring.datasource.url=jdbc:mysql://localhost:3306/votingdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Vetri@2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vetrisharma4533@gmail.com
spring.mail.password=ghydtnefrhdgmfkg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

facepp.api.key=YOUR_KEY
facepp.api.secret=YOUR_SECRET
facepp.api.url=https://api-cn.faceplusplus.com/facepp/v3


otp.expiry.minutes=5 


