spring.application.name=voting

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:9095}

brevo.api.key=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
brevo.sender.email=vetri.mec2028@gmail.com

facepp.api.key=${FACEPP_API_KEY:none}
facepp.api.secret=${FACEPP_API_SECRET:none}
facepp.api.url=https://api-us.faceplusplus.com/facepp/v3

otp.expiry.minutes=5